version: "{build}"
build_script:
- cmd: >-
    set MAVEN_VERSION=3.5.0

    choco install maven -version %MAVEN_VERSION%

    set JAVA_HOME=C:\Program Files\Java\jdk1.8.0

    set PATH=%PATH%;C:\bin\apache-maven-%MAVEN_VERSION%\bin

    mvn install --quiet --batch-mode
